export {
  serviceReducer,
  addAdress,
  changeAdressCity,
  changeCallMethod,
  changeWorkUnit,
  deleteAdress,
  hasPhoto,
  isVerified,
  selectCityApplication,
  setAddress,
  setDescptiption,
  setPrice,
  hasReview,
} from './service';
